# make -s -C 
# /home/chenyinhua/sda3/cyhos/os-workbench-2022/amgame/../abstract-machine/klib
# archive
NAME = klib
SRCS = $(shell find src/ -name "*.c")

# NAME = klib
# MAKECMDGOALS = archive
include $(AM_HOME)/Makefile
