# make -s -C 
# /home/chenyinhua/sda3/cyhos/os-workbench-2022/amgame/../abstract-machine/am 
# archive
NAME     := am
SRCS      = $(addprefix src/, $(AM_SRCS))
INC_PATH += $(AM_HOME)/am/src

# NAME     := am
# MAKECMDGOALS = archive
include $(AM_HOME)/Makefile
